FEATURE: Index page if cache was cleared
Codappix/search_core pull request #133
Opened 2018-03-08 20:03 UTC by DanielSiepmann

we use the cache clear hook to index pages whenever the cache was
cleared.
This makes it possible to cover some cases like changing content on a
page. But also if an integrator configures to clear additional pages.

This is limited as we can not handle cache tags at the moment.

Resolves: #131

2018-03-08 20:03 UTC, DanielSiepmann commented
@martinhummer can you check whether this works for you? I'll only merge if it's working for you, too.

2018-03-09 08:38 UTC, martinhummer requested changes
The Cache Hook works for me as expected!

While testing i figured out, that everytime a tt_content record gets saved the PagesIndexer->fetchContentForPage() fetches all available tt_content records of all pages and tries to index them.
A simple check for $contentElement['pid'] === $uid is missing here.

2018-03-13 19:37 UTC, DanielSiepmann commented
Thanks @martinhummer I saw the bug while refactoring to support both TYPO3 LTS versions and opened #135. This is not related to this Pull Request and will be fixed in a separate PR.

Once #136 is merged, I'll check and fix the broken tests and merge. In the meantime, you can use the diff at Github if you wish.

2018-03-14 10:33 UTC, justusmoroni approved these changes

2018-03-14 10:37 UTC, merged