BUGFIX: Do not resolve inputDateTime as relation
Codappix/search_core pull request #150
Opened 2018-04-01 09:31 UTC by DanielSiepmann

Add test which checks this behaviour.
Exclude inputDateTime from relation resolving.

Resolves #147

2018-04-06 10:09 UTC, martinhummer commented
I think the TCA Config is not correct.
I made a new version of the test, which uses the TCA config for tt_content field 'starttime' in 8.7.12 LTS:
https://github.com/martinhummer/search_core/blob/develop/Tests/Unit/Domain/Index/TcaIndexer/RelationResolverTest.php

This test will fail, because `BackendUtility::getProcessedValueExtra` returns a String like '06-04-18 10:36' and not a timestamp.

Do you think it would be possible to exclude inputDateTime fields completely from this processing and return the (int) timestamp as it is in the database.

2018-04-10 15:27 UTC, DanielSiepmann commented
I can't see any difference of the TCA Configuration. Without the change to skip the renderType I'll receive an empty value for `starttime` in the test. With the change I'll receive the original value. Perhaps we can chat on that to make sure it works as expected?

2018-04-12 09:45 UTC, justusmoroni requested changes

2018-04-12 09:45 UTC, leonmrni commented on Tests/Unit/Domain/Index/TcaIndexer/RelationResolverTest.php
> +            'starttime'
Shouldn't there be a more understandable message?

2018-04-12 09:45 UTC, leonmrni commented on Tests/Unit/Domain/Index/TcaIndexer/RelationResolverTest.php
> +            'starttime'
Like here?
https://github.com/Codappix/search_core/pull/152/files#diff-996a498714afe5c8a5c1802452779dcbR89

2018-04-12 10:14 UTC, justusmoroni approved these changes

2018-04-19 15:38 UTC, DanielSiepmann commented
We will keep the test, but will not process this issue itself anymore. Instead, see the issue, we will resolve this by working on #149 .

2018-04-19 15:38 UTC, closed without merging