Feature: Index pages instead of tt_content
Codappix/search_core pull request #58
Opened 2017-07-13 12:56 UTC by DanielSiepmann

As that makes much more sense. Still content is added to each page.
Also an abstract is added, where the fields used are configurable.

2017-07-25 13:38 UTC, justusmoroni requested changes

2017-07-25 13:38 UTC, leonmrni commented on Classes/Domain/Index/AbstractIndexer.php
> +    protected $identifier;
In other parts of code you initialized it with an empty string.
Shouldn't this be consistent?

2017-07-25 13:38 UTC, leonmrni commented on Classes/Domain/Index/TcaIndexer/PagesIndexer.php
> +        $possibleTitleFields = ['nav_title', 'tx_tqseo_pagetitle_rel', 'title'];
Should this be hardcoded?
We should move this to an configuration.

2017-07-25 13:38 UTC, leonmrni commented on Configuration/TypoScript/constants.txt
> +                    additionalWhereClause = pages.doktype NOT IN (3, 199, 6, 254, 255, 199)
`199` is in list multiple times.
Maybe sort it?

2017-07-25 13:38 UTC, leonmrni commented on Tests/Functional/Fixtures/Indexing/IndexTcaTable.xml
> +        <bodytext>this is the content of header content element that should not get indexed</bodytext>
What?

Fix in `Tests/Functional/Indexing/PagesIndexerTest.php` line 53 as well.

2017-07-25 13:42 UTC, DanielSiepmann commented on Classes/Domain/Index/TcaIndexer/PagesIndexer.php
> +        $possibleTitleFields = ['nav_title', 'tx_tqseo_pagetitle_rel', 'title'];
Yes, but for now this should be fine as two are core fields and one is just a supported extension. Once needed we can shift this to configuration with default setup.

2017-07-27 14:21 UTC, closed without merging

2017-07-27 14:28 UTC, DanielSiepmann commented on Configuration/TypoScript/constants.txt
> +                    additionalWhereClause = pages.doktype NOT IN (3, 199, 6, 254, 255, 199)
Sorting is done based on page type grouping, not the identifier. I've removed the second 199.

2017-07-27 14:31 UTC, DanielSiepmann commented on Tests/Functional/Fixtures/Indexing/IndexTcaTable.xml
> +        <bodytext>this is the content of header content element that should not get indexed</bodytext>
Nothing to fix in test, as this content element is NOT indexed due to the CType, while the header element is indexed.

But of course I've fixed the content element type in bodytext.