Feature: Spell check
Codappix/search_core pull request #77
Opened 2017-08-01 15:17 UTC by DanielSiepmann

Allow elasticsearch to suggest spelling correction.

Also introduce new concept of dataProcessing as done in TYPO3.

2017-08-10 21:04 UTC, justusmoroni requested changes

2017-08-10 21:04 UTC, leonmrni commented on Classes/DataProcessing/ProcessorInterface.php
> + * All DataProcessing Processor should implement this interface, otherwise they
`Processor` plural form is needed here, right?

2017-08-10 21:04 UTC, leonmrni commented on Classes/Domain/Search/QueryFactory.php
> +     * @param SearchRequestInterface $searchRequest
What is returned here?

2017-08-10 21:04 UTC, leonmrni commented on Classes/Domain/Search/QueryFactory.php
> +     */
What is returned here?

2017-08-10 21:04 UTC, leonmrni commented on Documentation/source/configuration.rst
> +The following sections containsthe different options grouped by their applied area, e.g. for
Missing whitespace between `contains` and `the`.

2017-08-15 06:26 UTC, DanielSiepmann commented on Classes/Domain/Search/QueryFactory.php
> +     */
Nothing, like most other methods in this class.

2017-08-15 06:28 UTC, DanielSiepmann commented on Classes/Domain/Search/QueryFactory.php
> +     * @param SearchRequestInterface $searchRequest
I've added the return type.

2017-08-29 08:12 UTC, justusmoroni approved these changes

2018-03-06 12:09 UTC, DanielSiepmann commented
This feature didn't make it in time.

We do not try to finish it yet and therefore close it.

2018-03-06 12:09 UTC, closed without merging