FEATURE: Implement necessary logic to support PaginateViewHelper
Codappix/search_core pull request #82
Opened 2017-08-08 15:18 UTC by DanielSiepmann

2017-08-10 06:56 UTC, DanielSiepmann commented
@leonmrni please check codacy issues. In my opinion all issues are related to API of TYPO3 and can not be influenced by us.

2017-08-10 20:46 UTC, justusmoroni requested changes

2017-08-10 20:46 UTC, leonmrni commented on Classes/Domain/Search/QueryFactory.php
> +                            ],
The indentation looks strange. It's wrong, right?

2017-08-10 20:46 UTC, leonmrni commented on Classes/Domain/Search/QueryFactory.php
> +                    ],
Also check indentation here.

2017-08-25 12:42 UTC, justusmoroni approved these changes

2017-08-29 07:25 UTC, merged